export const SET_NETWORK_INFO = 'SET_NETWORK_INFO'
export const SET_HOST_INFO = 'SET_HOST_INFO'
export const SET_PUBLIC_IP = 'SET_PUBLIC_IP'
export const ADD_DEVICE = 'ADD_DEVICE'
export const UPDATE_NAME = 'UPDATE_NAME'
export const UPDATE_GW_INFO = 'UPDATE_GW_INFO'
